export const products = [
  {
    name: "Bone",
    img: "./assets/bone.jpg",
    category: "toy",
    description: "A fun rubbery dog bone for your furry friend.",
    price: 5.99,
  },
  {
    name: "Fairy Costume",
    img: "./assets/dogclothes.jpg",
    category: "clothes",
    description: "A cute little fairy costume for your doggie.",
    price: 19.99,
  },
  {
    name: "Champion Hoodie",
    img: "./assets/dogclothes1.jpg",
    category: "clothes",
    description: "Keep your dog looking cool with this Champion hoodie! ",
    price: 25.99,
  },
  {
    name: "Overalls",
    img: "./assets/dogclothes2.jpg",
    category: "clothes",
    description: "Have your dog join you on the farm with some cool overalls.",
    price: 29.99,
  },
  {
    name: "Turtleneck",
    img: "./assets/dogclothes4.jpg",
    category: "clothes",
    description: "Up your dog's style with this hipster outfit.",
    price: 15.99,
  },

  {
    name: "Pawsific Treats",
    img: "./assets/dogfood1.jpg",
    category: "food",
    description: "Treat your dog to some deliciousness with Pawsific treats!",
    price: 15.99,
  },
  {
    name: "Dog Balls",
    img: "./assets/dogtoy1.jpg",
    category: "toy",
    description: "Add this essential toy to your dog's arsenal.",
    price: 7.99,
  },
  {
    name: "Breath Strips",
    img: "./assets/dogfood2.jpg",
    category: "food",
    description: "Give your dog some fresh breath with Breath Strips!",
    price: 8.99,
  },
  {
    name: "Butcher's can food",
    img: "./assets/dogfood3.jpg",
    category: "food",
    description: "Yummy canned food for your furry friend.",
    price: 3.99,
  },
  {
    name: "Cupcakes",
    img: "./assets/dogfood4.jpg",
    category: "food",
    description: "Frosted cupcakes for your furry little buddy.",
    price: 14.99,
  },
  {
    name: "Pink Zebra",
    img: "./assets/dogclothes3.jpg",
    category: "clothes",
    description: "Take your dog to fashion week with this pink zebra outfit.",
    price: 25.99,
  },
];
